# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.poly_tab <- function(G, correct = 1e-08) {
    .Call(`_polychoric_poly_tab`, G, correct)
}

.poly_xy <- function(X, Y, correct = 1e-08) {
    .Call(`_polychoric_poly_xy`, X, Y, correct)
}

.poly_df <- function(X, correct = 1e-08) {
    .Call(`_polychoric_poly_df`, X, correct)
}

.poly_tab_full <- function(G, correct) {
    .Call(`_polychoric_poly_tab_full`, G, correct)
}

.poly_xy_full <- function(x, y, correct = 1e-08) {
    .Call(`_polychoric_poly_xy_full`, x, y, correct)
}

.poly_df_full <- function(X, correct = 1e-08) {
    .Call(`_polychoric_poly_df_full`, X, correct)
}

.cor_polyserial <- function(x, d, correct = 1e-08) {
    .Call(`_polychoric_cor_polyserial`, x, d, correct)
}

.cor_polyserial_full <- function(x, d, correct = 1e-08) {
    .Call(`_polychoric_cor_polyserial_full`, x, d, correct)
}

